baseURL: ""
languageCode: en-us
title: Yueh Huan
theme: PaperMod
 # 主题名字，和themes文件夹下的一致

enableInlineShortcodes: true #允许内联短码
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45 # 谷歌统计
# Copyright: Wenjie Fan

paginate: 5    # 每页显示的文章数

minify:
    disableXML: true
    # minifyOutput: true

permalinks: #浏览器链接显示方式
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

languages:
    en:
      languageName: "English"
      # contentDir: content/english
      weight: 1
      profileMode:
        enabled: true
<<<<<<< HEAD
        title: Yueh Huan
        subtitle: "MSBA @ UCSD"
        imageUrl: "self_image.jpeg" #图片放在static/img/Q.gif
=======
        title: Yueh-Huan
        subtitle: "MSBA @ UCSD"
        imageUrl: "1629806540326.jpeg" #图片放在static/img/Q.gif
>>>>>>> 04c0eff (first commit)
        imageTitle: 
        imageWidth: 225
        imageHeight: 225
        buttons:
          - name: About
            url: about
          - name: Projects
            url: posts
          - name: CV
<<<<<<< HEAD
            url: about/Wenjie_Fan.pdf
=======
            url: about/Yuehhuan_resume.pdf
>>>>>>> 04c0eff (first commit)
      menu:
        main:
          - identifier: home
            name: Home
            url: /
            weight: 1
          - identifier: about
            name: About
            url: about
            weight: 2
          - identifier: posts
            name: Projects
            url: posts
            weight: 10
<<<<<<< HEAD
          - identifier: photos
            name: Photographs
            url: photos
            weight: 20
=======
>>>>>>> 04c0eff (first commit)
          - identifier: contact
            name: Contact
            url: contact
            weight: 100


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "这是一个纯粹的博客......"
<<<<<<< HEAD
    author: Wenjie
=======
    author: Yueh-Huan
>>>>>>> 04c0eff (first commit)
    # author: ["Me", "You"] # multiple authors
    defaultTheme: auto  # defaultTheme: light or  dark 
    disableThemeToggle: false
    DateFormat: "2006-01-02"
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecialistPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: false # 隐藏页脚
    ShowWordCounts: true
    VisitCount: true

    ShowLastMod: true #显示文章更新时间

    ShowToc: true # 显示目录
    TocOpen: true # 自动展开目录

    comments: true
    
    socialIcons:
        - name: linkedin
<<<<<<< HEAD
          url: "https://github.com/xyming108"
        - name: facebook
          url: "https://www.facebook.com/profile.php?id=100027782410997"
        - name: WeChat
          url: "img/wechat.png"
        - name: email
          url: "wenjie.fan@keble.ox.ac.uk"
=======
          url: "https://www.linkedin.com/in/y6ho/"
        - name: facebook
          url: "https://www.facebook.com/profile.php?id=100000280841885"
        - name: github
          url: "https://github.com/yueeeeeee87"
        - name: email
          url: "y6ho@ucsd.edu"
>>>>>>> 04c0eff (first commit)

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    label:
      text: "Yueh Huan's Page"
      #icon: "img/Q.gif"

    # analytics:  #谷歌分析
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        favicon: "img/Q.gif"
        favicon16x16: "img/Q.gif"
        favicon32x32: "img/Q.gif"
        apple_touch_icon: "Q.gif"
        safari_pinned_tab: "Q.gif"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 1
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary"]

    twikoo:
      version: 1.4.11

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
    highlight:
        # anchorLineNos: true
        codeFences: true  
        guessSyntax: true
        lineNos: true
        # noClasses: false
        # style: monokai
        style: darcula

        # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
        # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
        # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
        # lineNoStart：行号从编号几开始，一般从 1 开始。
        # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
        # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
        # noClasses：使用 class 标签，而不是内嵌的内联样式

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true